In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/AMS_SampleDataSet.csv', header=4)
column_names = df.columns
print(column_names)
drop_columns = [column_names[i] for i in [4]]
df.drop(drop_columns, inplace=True, axis=1)

# Only KW
df = df[df['Unit of Measurement'] == 'KW_DEL']

# Separate meters
meter_1362 = df[df['Meter Number'] == 'V349N-001362']
meter_17182 = df[df['Meter Number'] == 'V349N-017182']

# Delete now unnecessary columns
new_meter1 = meter_1362.drop(['Service Account No', 'Date', 'Meter Number', 'Unit of Measurement'], axis=1)
new_meter2 = meter_17182.drop(['Service Account No', 'Date', 'Meter Number', 'Unit of Measurement'], axis=1)

new_meter_stack1 = pd.DataFrame(new_meter1.stack(), columns = ['Meter 1362'])
new_meter_stack1.reset_index(drop=True, inplace=True)
new_meter_stack2 = pd.DataFrame(new_meter2.stack(), columns = ['Meter 17182'])
new_meter_stack2.reset_index(drop=True, inplace=True)

#date = meter_1362['Date']
#time = pd.Index[df[1]]

meter_final = pd.concat([new_meter_stack1,new_meter_stack2], axis =1, sort=False)

#Deal with NAs
no_missing_values = meter_final.dropna(axis=0)
#meter_17182.head(10)

#plotting
# 8 AM is 32 (0 to 32)
# 5 PM is 68 
#no_missing_values.set_index([date])

#fill NAs with mean of column
#df['col'] = df['col'].fillna(df['col'].mean()) #OR
#df.fillna(method='pad',limit=1)

Index(['Service Account No', 'Date', 'Meter Number', 'Unit of Measurement',
       'Unnamed: 4', '00:00', '00:15', '00:30', '00:45', '01:00',
       ...
       '21:30', '21:45', '22:00', '22:15', '22:30', '22:45', '23:00', '23:15',
       '23:30', '23:45'],
      dtype='object', length=101)

In [35]:
#ALL DATA IN COLUMNS NOT INDEX

df = pd.read_csv('data/data2.csv')
column_names = df.columns
drop_columns = [column_names[i] for i in [4]]
df.drop(drop_columns, inplace=True, axis=1)

# Only KW
df = df[df['Unit of Measurement'] == 'KW_DEL']

# Separate meters
meter_1362 = df[df['Meter Number'] == 'V349N-001362']
meter_17182 = df[df['Meter Number'] == 'V349N-017182']

# Delete now unnecessary columns
new_meter1 = meter_1362.drop(['Service Account No','Meter Number', 'Unit of Measurement'], axis=1)
new_meter10 = new_meter1.set_index(['Date'])
new_meter2 = meter_17182.drop(['Service Account No', 'Meter Number', 'Unit of Measurement'], axis=1)
new_meter20 = new_meter2.set_index(['Date'])

new_meter_stack1 = pd.DataFrame(new_meter10.stack(), columns = ['Meter 1362'])
new_meter_stack2 = pd.DataFrame(new_meter20.stack(), columns = ['Meter 17182'])

meter_final = pd.concat([new_meter_stack1,new_meter_stack2], axis =1, sort=False)
meter_final.reset_index(level=0, inplace=True)
meter_final['Time'] = meter_final.index
meter_final.reset_index(drop=True, inplace=True)

meter_final['Date'] = pd.to_datetime(meter_final['Date'])
meter_final['Time'] = pd.to_datetime(meter_final['Time'])
meter_final['Day of Week'] = meter_final['Date'].dt.weekday_name
meter_final.sort_values(by='Date')

#Deal with NAs
no_missing_values = meter_final.dropna(axis=0)

#DLS
#DLS = (no_missing_values['2014-11-3':'2015-3-10'])
#for i in no_missing_values:
 #   if DLS:
  #      no_missing_values['Time'] += time(0,1,0)
    
DLS.head(10)

#Daylight savings
#meter_final['Time'] = meter_final['Time'].tz_localize('PST', ambiguous='infer')
#for i in no_missing_values:
    #if no_missing_values['Date'] >

#plotting
#for i in no_missing_values:
 #   if no_missing_values['Day of Week'] == 'Saturday' or 'Sunday':
 #       no_missing_values = no_missing_values.drop[i]

# 8 AM is 32 (0 to 32)
# 5 PM is 68 
#no_missing_values.set_index([date])

#fill NAs with mean of column
#df['col'] = df['col'].fillna(df['col'].mean()) #OR
#df.fillna(method='pad',limit=1)

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.numeric.Int64Index'> with these indexers [2014-11-3] of <class 'str'>

In [42]:
#WORK OFF THIS. dates in right order

import matplotlib as mp
import pylab as P

df = pd.read_csv('data/data2.csv')
column_names = df.columns
drop_columns = [column_names[i] for i in [4]]
df.drop(drop_columns, inplace=True, axis=1)

# Only KW
df = df[df['Unit of Measurement'] == 'KW_DEL']
df['Datetime'] = pd.to_datetime(df['Date'])

# Separate meters
meter_1362 = df[df['Meter Number'] == 'V349N-001362']
meter_17182 = df[df['Meter Number'] == 'V349N-017182']

# Delete now unnecessary columns
new_meter1 = meter_1362.drop(['Service Account No', 'Date','Meter Number', 'Unit of Measurement'], axis=1)
new_meter10 = new_meter1.set_index(['Datetime'])
new_meter2 = meter_17182.drop(['Service Account No', 'Date','Meter Number', 'Unit of Measurement'], axis=1)
new_meter20 = new_meter2.set_index(['Datetime'])

#Interpolate NAs with average of that day
new_meter10.fillna(new_meter10.mean(), axis='rows', inplace=True)
new_meter20.fillna(new_meter20.mean(), axis='rows',inplace=True)

#Adjust for daylight savings
#meter_final['Time'] = meter_final['Time'].tz_localize('PST', ambiguous='infer')

#stack data chronologically
new_meter_stack1 = pd.DataFrame(new_meter10.stack(), columns = ['Meter 1362'])
new_meter_stack2 = pd.DataFrame(new_meter20.stack(), columns = ['Meter 17182'])

#concat both meters together
meter_final = pd.concat([new_meter_stack1,new_meter_stack2], axis =1, sort=False)

meter_final.reset_index(level=0, inplace=True) #make datetime a column
meter_final['Time'] = meter_final.index #make time a column
meter_final.reset_index(drop=True, inplace=True)

meter_final['Day of Week'] = meter_final['Datetime'].dt.weekday_name # add weekday names

meter_final2 = meter_final.set_index(['Datetime','Time', 'Day of Week']) #set index

meter_final2.head(10)
# OR ADJUST FOR DAYLIGHT SAVINGS HERE??
#DLS = meter_final, index=('Datetime','Time')
#DLS = meter_final2.tz_localize(level=0,'PST', ambiguous='infer')
#for x in Time

#np.where()
#plotting

week = no_missing_values.drop(index='Saturday', level=2)
week = week.drop(index='Sunday',level=2)
weekday = week.drop(index =['0:00','0:15','0:30','0:45','1:00','1:15','1:30','1:45', '2:00', '2:15','2:30','2:45','3:00','3:15','3:30','3:45','4:00','4:15', '4:30','4:45','5:00', '5:15', '5:30', '5:45','6:00','6:15','6:30','6:45','7:00','7:15','7:30','7:45','17:00','17:15','17:30','17:45','18:00','18:15','18:30','18:45','19:00','19:15','19:30','19:45','20:00','20:15','20:30','20:45','21:00','21:15','21:30','21:45','22:00','22:15','22:30','22:45','23:00','23:15','23:30','23:45'],level=1)

#percentile5 = mp.mlab.prctile(weekday, p=(0.05))
#weekday.plot()

                             Meter 1362  Meter 17182
Datetime   Time Day of Week
2014-09-13 0:00 Saturday          108.0         28.8
           0:15 Saturday          110.4         28.8
           0:30 Saturday          117.6         31.2
           0:45 Saturday          110.4         24.0
           1:00 Saturday          112.8         26.4
           1:15 Saturday          115.2         28.8
           1:30 Saturday          115.2         24.0
           1:45 Saturday          115.2         26.4
           2:00 Saturday          112.8         28.8
           2:15 Saturday          115.2         24.0

In [40]:
#datetimes

from datetime import time,datetime
import pytz

df = pd.read_csv('data/data2.csv')
column_names = df.columns
drop_columns = [column_names[i] for i in [4]]
df.drop(drop_columns, inplace=True, axis=1)

# Only KW
df = df[df['Unit of Measurement'] == 'KW_DEL']
#df['Datetime'] = pd.to_datetime(df['Date'])

# Separate meters
meter_1362 = df[df['Meter Number'] == 'V349N-001362']
meter_17182 = df[df['Meter Number'] == 'V349N-017182']

# Delete now unnecessary columns
new_meter1 = meter_1362.drop(['Service Account No','Meter Number', 'Unit of Measurement'], axis=1)
new_meter10 = new_meter1.set_index(['Date'])
new_meter2 = meter_17182.drop(['Service Account No','Meter Number', 'Unit of Measurement'], axis=1)
new_meter20 = new_meter2.set_index(['Date'])

new_meter_stack1 = pd.DataFrame(new_meter10.stack(), columns = ['Meter 1362'])
new_meter_stack2 = pd.DataFrame(new_meter20.stack(), columns = ['Meter 17182'])

meter_final = pd.concat([new_meter_stack1,new_meter_stack2], axis =1, sort=False)

meter_final.reset_index(level=0, inplace=True) #make datetime a column
meter_final['Time'] = meter_final.index #make time a column
meter_final['Datetime'] = meter_final['Date'] + ' ' + meter_final['Time']
meter_final['Datetime'] = pd.to_datetime(meter_final['Datetime'])
meter_final.reset_index(drop=True, inplace=True)
meter_final.head(10)

meter_final['Day of Week'] = meter_final['Datetime'].dt.weekday_name


meter_final2 = meter_final.set_index(['Datetime', 'Day of Week'])
#meter_final2 = meter_final.set_index(['Datetime'])
#DLS = meter_final2.tz_localize(tz='US/Pacific', ambiguous='infer')

#meter_final2.sort_values(by='Datetime')
#Deal with NAs
no_missing_values = meter_final2.dropna(axis=0)
print(no_missing_values)

#no_missing_values['Datetime'].tzinfo
#plotting

#week = no_missing_values.drop(index='Saturday', level=1)
#week = week.drop(index='Sunday',level=1)

#start_time = time(17,0,0)
#end_time = time(8,0,0)
#weekday = week.loc[(week.index < end_time) | (week.index > start_time)]
#weekday = week.drop(index ='0:00')

#for i in no_missing_values:
  #  if no_missing_values['Day of Week'] == 'Saturday' or 'Sunday':
   #     no_missing_values = no_missing_values.drop[i]

                                   Date  Meter 1362  Meter 17182   Time
Datetime            Day of Week
2015-01-01 00:00:00 Thursday     1/1/15        57.6         33.6   0:00
2015-01-01 00:15:00 Thursday     1/1/15        60.0         28.8   0:15
2015-01-01 00:30:00 Thursday     1/1/15        60.0         33.6   0:30
2015-01-01 00:45:00 Thursday     1/1/15        60.0         28.8   0:45
2015-01-01 10:00:00 Thursday     1/1/15        62.4         31.2  10:00
2015-01-01 10:15:00 Thursday     1/1/15        62.4         36.0  10:15
2015-01-01 10:30:00 Thursday     1/1/15        60.0         31.2  10:30
2015-01-01 10:45:00 Thursday     1/1/15        60.0         36.0  10:45
2015-01-01 11:00:00 Thursday     1/1/15        62.4         31.2  11:00
2015-01-01 11:15:00 Thursday     1/1/15        60.0         33.6  11:15
2015-01-01 11:30:00 Thursday     1/1/15        62.4         33.6  11:30
2015-01-01 11:45:00 Thursday     1/1/15        57.6         33.6  11:45
2015-01-01 12:00:00 Thursday     1/1/15        57.6         31.2  12:00
2015-01-01 12:15:00 Thursday     1/1/15        62.4         33.6  12:15
2015-01-01 12:30:00 Thursday     1/1/15        57.6         31.2  12:30
2015-01-01 12:45:00 Thursday     1/1/15        62.4         36.0  12:45
2015-01-01 13:00:00 Thursday     1/1/15        62.4         31.2  13:00
2015-01-01 13:15:00 Thursday     1/1/15        57.6         36.0  13:15
2015-01-01 13:30:00 Thursday     1/1/15        62.4         33.6  13:30
2015-01-01 13:45:00 Thursday     1/1/15        57.6         36.0  13:45
2015-01-01 14:00:00 Thursday     1/1/15        60.0         31.2  14:00
2015-01-01 14:15:00 Thursday     1/1/15        60.0         33.6  14:15
2015-01-01 14:30:00 Thursday     1/1/15        57.6         31.2  14:30
2015-01-01 14:45:00 Thursday     1/1/15        57.6         36.0  14:45
2015-01-01 15:00:00 Thursday     1/1/15        60.0         31.2  15:00
2015-01-01 15:15:00 Thursday     1/1/15        60.0         36.0  15:15
2015-01-01 15:30:00 Thursday     1/1/15        57.6         33.6  15:30
2015-01-01 15:45:00 Thursday     1/1/15        57.6         33.6  15:45
2015-01-01 16:00:00 Thursday     1/1/15        72.0         33.6  16:00
2015-01-01 16:15:00 Thursday     1/1/15        91.2         36.0  16:15
...                                 ...         ...          ...    ...
2016-09-09 02:30:00 Friday       9/9/16        62.4        128.0   2:30
2016-09-09 02:45:00 Friday       9/9/16        62.4        128.0   2:45
2016-09-09 03:00:00 Friday       9/9/16        60.0        128.0   3:00
2016-09-09 03:15:00 Friday       9/9/16        62.4        128.0   3:15
2016-09-09 03:30:00 Friday       9/9/16        62.4        128.0   3:30
2016-09-09 03:45:00 Friday       9/9/16        67.2        128.0   3:45
2016-09-09 04:00:00 Friday       9/9/16        96.0        128.0   4:00
2016-09-09 04:15:00 Friday       9/9/16       136.8        128.0   4:15
2016-09-09 04:30:00 Friday       9/9/16       129.6        128.0   4:30
2016-09-09 04:45:00 Friday       9/9/16       115.2        128.0   4:45
2016-09-09 05:00:00 Friday       9/9/16       120.0        128.0   5:00
2016-09-09 05:15:00 Friday       9/9/16       120.0        128.0   5:15
2016-09-09 05:30:00 Friday       9/9/16       129.6        128.0   5:30
2016-09-09 05:45:00 Friday       9/9/16       132.0        144.0   5:45
2016-09-09 06:00:00 Friday       9/9/16       314.4        144.0   6:00
2016-09-09 06:15:00 Friday       9/9/16       276.0        160.0   6:15
2016-09-09 06:30:00 Friday       9/9/16       261.6        176.0   6:30
2016-09-09 06:45:00 Friday       9/9/16       259.2        160.0   6:45
2016-09-09 07:00:00 Friday       9/9/16       261.6        176.0   7:00
2016-09-09 07:15:00 Friday       9/9/16       268.8        176.0   7:15
2016-09-09 07:30:00 Friday       9/9/16       266.4        192.0   7:30
2016-09-09 07:45:00 Friday       9/9/16       261.6        192.0   7:45
2016-09-09 08:00:00 Friday       9/9/16       268.8        192.0   8:00
2016-09-09 08:15:00 Friday       9/9/16       268.8        208.0   8:15
2016-09-09 08:30:00 Friday       9/9/16       273.6        224.0   8:30
2016-09-09 08:45:00 Friday       9/9/16       276.0        208.0   8:45
2016-09-09 09:00:00 Friday       9/9/16       271.2        240.0   9:00
2016-09-09 09:15:00 Friday       9/9/16       290.4        240.0   9:15
2016-09-09 09:30:00 Friday       9/9/16       304.8        224.0   9:30
2016-09-09 09:45:00 Friday       9/9/16       316.8        240.0   9:45

[69811 rows x 4 columns]

KeyError: 'Datetime'